#!/usr/bin/env php
<?php

use core\Db;
set_time_limit(0);
ini_set('memory_limit', '1024M');
ini_set("display_errors", "no");
error_reporting(E_ALL);
date_default_timezone_set('PRC');
define('APP_PATH', dirname(__FILE__).'/');
include_once 'core/init.php';

$spider = new \core\Spider();
$spider->start();

?>

